Virtualization Driver

diff --git a/vmm/lxc/deploy b/vmm/lxc/deploy
--- a/vmm/lxc/deploy
+++ b/vmm/lxc/deploy
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # -------------------------------------------------------------------------- #
-# Copyright 2002-2015, OpenNebula Project, OpenNebula Systems                #
+# Copyright 2014-2015, OpenNebula Project, OpenNebula Systems                #
 #                                                                            #
 # Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com              #
 #          José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
@@ -49,12 +49,14 @@ done < <($XPATH 	/VM/ID \
                        	/VM/TEMPLATE/NIC/MAC \
                         /VM/TEMPLATE/CONTEXT/ETH0_GATEWAY \
 			/VM/TEMPLATE/CONTEXT/DISK_ID \
-			/VM/TEMPLATE/DISK/TM_MAD \
+			/VM/TEMPLATE/DISK/TYPE \
 			/VM/TEMPLATE/DISK/IMAGE_ID \
 			/VM/HISTORY_RECORDS/HISTORY/DS_ID \
 			/VM/TEMPLATE/GRAPHICS/PASSWD \
 			/VM/TEMPLATE/GRAPHICS/PORT \
 			/VM/TEMPLATE/DISK/SOURCE \
+			/VM/TEMPLATE/DISK/PERSISTENT \
+			/VM/TEMPLATE/DISK/CLONE \
 			/VM/TEMPLATE/GRAPHICS/LISTEN)
 
 VM_ID="${XPATH_ELEMENTS[0]}"
@@ -65,15 +67,20 @@ VM_NIC_NETMASK="${XPATH_ELEMENTS[4]}"
 VM_NIC_MAC="${XPATH_ELEMENTS[5]}"
 VM_NIC_GATEWAY="${XPATH_ELEMENTS[6]}"
 VM_DISKS="${XPATH_ELEMENTS[7]}"
-VM_TM_DRIVER="${XPATH_ELEMENTS[8]}"
+VM_DISK_TYPE="${XPATH_ELEMENTS[8]}"
 IMAGE_ID="${XPATH_ELEMENTS[9]}"
 SYSTEM_DATASTORE_ID="${XPATH_ELEMENTS[10]}"
 VM_VNC_PASSWD="${XPATH_ELEMENTS[11]}"
 VM_VNC_PORT="${XPATH_ELEMENTS[12]}"
 VM_DISK_SOURCE="${XPATH_ELEMENTS[13]}"
-VM_VNC_LISTEN="${XPATH_ELEMENTS[14]}"
+VM_DISK_PERSISTENT="${XPATH_ELEMENTS[14]}"
+VM_DISK_CLONE="${XPATH_ELEMENTS[15]}"
+VM_VNC_LISTEN="${XPATH_ELEMENTS[16]}"
 
-VM_HOSTNAME_FIXED=${VM_HOSTNAME// /-}
+VM_HOSTNAME=${VM_HOSTNAME// /-}
+VM_HOSTNAME_FIXED=${VM_HOSTNAME//_/-}
+
+CEPH_AUTH=$(grep CEPH_ARGS /etc/environment | cut -d '"' -f 2)
 
 # Create the directory where the containers will be stored #
 
@@ -92,7 +99,13 @@ fi
 
 TOTAL_iFACE=$(xmlstarlet sel -t -v "count(/VM/TEMPLATE/NIC/IP)" /var/lib/one/vms/${VM_ID}/deployment.$DEPLOY_NUM)
 
+NIC_ID_LIST=$(xmlstarlet sel -t -v "/VM/TEMPLATE/NIC/NIC_ID" /var/lib/one/vms/${VM_ID}/deployment.$DEPLOY_NUM)
 
+iFACE=0
+while read rNIC; do
+	NIC_ID[$iFACE]=$rNIC
+	let iFACE=iFACE+1
+done < <(echo -e "$NIC_ID_LIST")
 
 #----
 # IP
@@ -132,7 +145,8 @@ while [ $iFACE -lt $TOTAL_iFACE ]; do
                 		192) let nbits+=2; break ;;
                 		128) let nbits+=1; break ;;
                 		0);;
-                		*) echo "{$MASK_ETH[$iFACE]} is an invalid netmask. Setting up /24" && export DEFAULT_NETMASK=24;;
+                		*) 
+echo "{$MASK_ETH[$iFACE]} is an invalid netmask. Setting up /24" && export DEFAULT_NETMASK=24;;
        			esac
 		done
 
@@ -214,26 +228,28 @@ done
 #CONFIG-FILE
 #------------
 
-while [ $iFACE -gt "0" ];do
-let iFACE=iFACE-1
+cnt_iface=0
+
+while [ $cnt_iface -lt $iFACE ];do
 NET_CONFIG="$NET_CONFIG $(cat << EOF
 
-
-# ETH${iFACE}
+# ETH${cnt_iface}
 lxc.utsname = $VM_HOSTNAME
 lxc.network.type = veth
-lxc.network.veth.pair= ${VM_ID}-eth$iFACE
+lxc.network.veth.pair= ${VM_ID}-eth${NIC_ID[$cnt_iface]}
 lxc.network.flags = up
-lxc.network.link = ${BR_ETH[$iFACE]}
-lxc.network.hwaddr = ${MAC_ETH[$iFACE]}
-lxc.network.ipv4 = ${IP_ETH[$iFACE]}/${CIDR_MASK_ETH[$iFACE]}
-${CONFIG_GW_ETH[$iFACE]}
+lxc.network.name = eth${NIC_ID[$cnt_iface]}
+lxc.network.link = ${BR_ETH[$cnt_iface]}
+lxc.network.hwaddr = ${MAC_ETH[$cnt_iface]}
+lxc.network.ipv4 = ${IP_ETH[$cnt_iface]}/${CIDR_MASK_ETH[$cnt_iface]}
+${CONFIG_GW_ETH[$cnt_iface]}
 EOF
 )"
-done
+let cnt_iface=cnt_iface+1
+done < <(echo -e "$XML_PARSE")
 
 #############################################################################
-#		        FSTAB. Default option. Not used                     #
+#		        FSTAB. Not used                                     #
 #############################################################################
 
 # Attach extra drives to containers, fstab way #
@@ -257,12 +273,62 @@ done
 #			rootfs						  #
 ###########################################################################
 
-case $VM_TM_DRIVER in
-	shared) rootfs=loop:/var/lib/one/datastores/$SYSTEM_DATASTORE_ID/$VM_ID/disk.0;;
-	fs_lvm) rootfs=/dev/vg-one-0/lv-one-${VM_ID}-0;;
-	lvm) rootfs=/dev/opennebula/lv-one-${IMAGE_ID}-${VM_ID};;
-	ceph) rbd map $VM_DISK_SOURCE;
-		rootfs = `rbd showmapped | grep one-$IMAGE_ID | awk '{print $5}'`;;
+case $VM_DISK_TYPE in
+	FILE) 	rootfs=loop:/var/lib/one/datastores/$SYSTEM_DATASTORE_ID/$VM_ID/disk.0
+		sudo echo "lxc-start -d -n one-$VM_ID" > /tmp/rc.local.opennebula_temp
+		sudo echo "#--------------------------------------------" >> /tmp/rc.local.opennebula_temp
+		line_number=$(grep -in "exit 0" /etc/rc.local | awk 'NR==2' | cut -d ':' -f 1)
+                let line_number=line_number-1
+                sudo sed -i "$line_number r /tmp/rc.local.opennebula_temp" /etc/rc.local
+		echo "just_reboot=0" > /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "if [ \"\$just_reboot\" = \"0\" ]; then" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "start_line=\$(grep -in \"lxc-start -d -n one-$VM_ID\" /etc/rc.local | cut -d ':' -f 1)" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "end_line=\$((\$start_line+1))" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "sed \"\$start_line,\$end_line d\" /etc/rc.local > /tmp/rc.local.tmp1 && mv /tmp/rc.local.tmp1 /etc/rc.local" >> /var/lib/lxc/one-$VM_ID/stop-hook
+		echo "sed \"\$start_line,\$end_line d\" /etc/rc.local > /tmp/rc.local.tmp1 && mv /tmp/rc.local.tmp1 /etc/rc.local" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "chmod 755 /etc/rc.local" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "fi" >> /var/lib/lxc/one-$VM_ID/stop-hook;;
+	BLOCK) 	rootfs=/dev/vg-one-0/lv-one-${VM_ID}-0
+		sudo echo "lxc-start -d -n one-$VM_ID" > /tmp/rc.local.opennebula_temp
+		sudo echo "#--------------------------------------------" >> /tmp/rc.local.opennebula_temp
+		line_number=$(grep -in "exit 0" /etc/rc.local | awk 'NR==2' | cut -d ':' -f 1)
+                let line_number=line_number-1
+                sudo sed -i "$line_number r /tmp/rc.local.opennebula_temp" /etc/rc.local
+		echo "just_reboot=0" > /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "if [ -z \$just_reboot ]; then" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "start_line=\$(grep -in \"lxc-start -d -n one-$VM_ID\" /etc/rc.local | cut -d ':' -f 1)" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "end_line=\$((\$start_line+1))" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "sed \"\$start_line,\$end_line d\" /etc/rc.local > /tmp/rc.local.tmp1 && mv /tmp/rc.local.tmp1 /etc/rc.local" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "chmod 755 /etc/rc.local" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "fi" >> /var/lib/lxc/one-$VM_ID/stop-hook;;
+	RBD) if [ "${VM_DISK_CLONE}" = "YES" ]; then
+ 			VM_DISK_SOURCE="${VM_DISK_SOURCE}-${VM_ID}-0"
+			fi
+		rootfs=`rbd showmapped | grep $VM_DISK_SOURCE | awk 'NR==1' | awk '{ print $5 }'`
+		if [ -z $rootfs ]; then
+			sudo -E rbd map $VM_DISK_SOURCE;
+                        rootfs=$(rbd showmapped | grep one-$IMAGE_ID | awk 'NR==1' | awk '{ print $5 }')
+                fi
+		echo "rbd map $CEPH_AUTH $VM_DISK_SOURCE" > /tmp/rc.local.opennebula_temp
+		echo "rootfs=\$(rbd showmapped | grep one-$IMAGE_ID | awk 'NR==1' | awk '{ print \$5 }')" >> /tmp/rc.local.opennebula_temp
+		echo "rootfs=\"lxc.rootfs = \$rootfs\"" >> /tmp/rc.local.opennebula_temp
+		echo "line=\$(grep -in rootfs /var/lib/lxc/one-$VM_ID/config | cut -d ':' -f 1)" >> /tmp/rc.local.opennebula_temp
+		echo "sed \"\$line d\" /var/lib/lxc/one-$VM_ID/config > /tmp/one-$VM_ID-config-tmp && mv /tmp/one-$VM_ID-config-tmp /var/lib/lxc/one-$VM_ID/config" >> /tmp/rc.local.opennebula_temp
+		echo "sed -i \"\$line i \$rootfs\" /var/lib/lxc/one-$VM_ID/config" >> /tmp/rc.local.opennebula_temp
+		echo "lxc-start -d -n one-$VM_ID" >> /tmp/rc.local.opennebula_temp
+		sudo echo "#--------------------------------------------" >> /tmp/rc.local.opennebula_temp
+                line_number=$(grep -in "exit 0" /etc/rc.local | awk 'NR==2' | cut -d ':' -f 1)
+		let line_number=line_number-1
+                sudo sed -i "$line_number r /tmp/rc.local.opennebula_temp" /etc/rc.local
+		echo "just_reboot=0" > /var/lib/lxc/one-$VM_ID/stop-hook
+		echo "if [ \"\$just_reboot\" = \"0\" ]; then" >> /var/lib/lxc/one-$VM_ID/stop-hook
+		echo "sudo rbd unmap ${rootfs}" >> /var/lib/lxc/one-$VM_ID/stop-hook
+		echo "start_line=\$(grep -in \"rbd map $CEPH_AUTH $VM_DISK_SOURCE\" /etc/rc.local | cut -d ':' -f 1)" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "end_line=\$((\$start_line+7))" >> /var/lib/lxc/one-$VM_ID/stop-hook
+                echo "sed \"\$start_line,\$end_line d\" /etc/rc.local > /tmp/rc.local.tmp1 && mv /tmp/rc.local.tmp1 /etc/rc.local" >> /var/lib/lxc/one-$VM_ID/stop-hook
+		echo "chmod 755 /etc/rc.local" >> /var/lib/lxc/one-$VM_ID/stop-hook
+		echo "fi" >> /var/lib/lxc/one-$VM_ID/stop-hook;;
+
 esac
 
 ##############################################################################
@@ -271,14 +337,14 @@ esac
 
 cat > /var/lib/lxc/one-$VM_ID/start-hook <<EOF
 #!/bin/bash
-sed -i s/"lxc.start.auto = 0"/"lxc.start.auto = 1"/g /var/lib/lxc/one-$VM_ID/config
+#sed -i s/"lxc.start.auto = 0"/"lxc.start.auto = 1"/g /var/lib/lxc/one-$VM_ID/config
 at now -f /var/lib/lxc/one-$VM_ID/vnc
 EOF
 
-cat > /var/lib/lxc/one-$VM_ID/stop-hook <<EOF
+#cat > /var/lib/lxc/one-$VM_ID/stop-hook <<EOF
 #!/bin/bash
-sed -i s/"lxc.start.auto = 1"/"lxc.start.auto = 0"/g /var/lib/lxc/one-$VM_ID/config
-EOF
+#sed -i s/"lxc.start.auto = 1"/"lxc.start.auto = 0"/g /var/lib/lxc/one-$VM_ID/config
+#EOF
 
 
 #######
@@ -293,14 +359,6 @@ VM_VNC_PASSWD=${VM_VNC_PASSWD}
 
 sudo lxc-wait -n one-$VM_ID -s RUNNING
 
-## VNC
-if [ -n "${VM_VNC_PASSWD}" ]; then
-sudo vncterm -timeout 0 -passwd ${VM_VNC_PASSWD} -rfbport $VM_VNC_PORT -c lxc-console -n one-$VM_ID &
-fi
-
-## Setting the VM Hostname after making sure there are no space chars on the hostname
-
-sudo lxc-attach -e -n one-$VM_ID -- hostname $VM_HOSTNAME_FIXED
 
 EOF
 
@@ -350,29 +408,111 @@ lxc.hook.post-stop = /var/lib/lxc/one-$VM_ID/stop-hook
 
 EOF
 
-##############################################################################
-#                  	    INICIAR CONTENEDOR VIRTUAL                       #
-##############################################################################
-
-exec_and_log "sudo lxc-start -d -n one-$VM_ID -f /var/lib/lxc/one-$VM_ID/config"
-sudo lxc-wait -n one-$VM_ID -s RUNNING
 
 ##############################################################################
 #                               ATACHAR HDDs                                 #
 ##############################################################################
 
-XML_PARSE=$(xmlstarlet sel -t -v "/VM/TEMPLATE/DISK/DISK_ID" /var/lib/one/vms/${VM_ID}/deployment.$DEPLOY_NUM)
+while read TYPE; do
+	DISK_TYPE[z++]="$TYPE"
+done < <(xmlstarlet sel -t -v "/VM/TEMPLATE/DISK/TYPE" -n /var/lib/one/vms/${VM_ID}/deployment.$DEPLOY_NUM)
 
-while read DISK_ID; do
-	if [ $DISK_ID -ne 0 ]; then
-		lvm=$(sudo lvdisplay | grep lv-one-${VM_ID}-$DISK_ID)
-		if [ -n "$lvm" ]; then
-			sudo lxc-device -n one-$VM_ID add /dev/vg-one-0/lv-one-${VM_ID}-$DISK_ID
-			sudo lxc-attach -n one-$VM_ID -- mount -o x-mount.mkdir /dev/vg-one-0/lv-one-${VM_ID}-$DISK_ID /media/$DISK_ID
-		else
-        		loop=$(sudo losetup -f --show /var/lib/one/datastores/0/$VM_ID/disk.$DISK_ID)
-			sudo lxc-device -n one-$VM_ID add $loop
-			sudo lxc-attach -n one-$VM_ID -- mount -o x-mount.mkdir $loop /media/$DISK_ID
+while read SOURCE; do
+	DISK_SOURCE[j++]="$SOURCE"
+done < <(xmlstarlet sel -t -v "/VM/TEMPLATE/DISK/SOURCE" -n /var/lib/one/vms/${VM_ID}/deployment.$DEPLOY_NUM)
+
+#while read PERSISTENT; do
+#        DISK_PERSISTENT[k++]="$PERSISTENT"
+#done < <(xmlstarlet sel -t -v "/VM/TEMPLATE/DISK/PERSISTENT" -n /var/lib/one/vms/${VM_ID}/deployment.$DEPLOY_NUM)
+
+while read CLONE; do
+        DISK_CLONE[l++]="$CLONE"
+done < <(xmlstarlet sel -t -v "/VM/TEMPLATE/DISK/CLONE" -n /var/lib/one/vms/${VM_ID}/deployment.$DEPLOY_NUM)
+
+
+
+
+XML_ELEMENT=0
+while read DSK_ID; do
+if [ $DSK_ID -ne 0 ]; then
+let XML_ELEMENT=XML_ELEMENT+1
+#sudo lxc-attach -n one-$VM_ID -- mkdir -p /media/$DSK_ID
+	case ${DISK_TYPE[${XML_ELEMENT}]} in
+        	FILE) loop=$(sudo losetup -f --show /var/lib/one/datastores/${SYSTEM_DATASTORE_ID}/${VM_ID}/disk.$DSK_ID)
+			echo "#--------------------Mounting disk $DSK_ID on one-${VM_ID}--------------------#" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "exists=\$(losetup -a | grep $loop | cut -d ':' -f 1)" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "if [ -z \$exists ]; then" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "losetup $loop /var/lib/one/datastores/${SYSTEM_DATASTORE_ID}/${VM_ID}/disk.$DSK_ID" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "fi" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "lxc-device -n one-$VM_ID add $loop" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "lxc-attach -n one-$VM_ID -- mkdir -p /media/$DSK_ID" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "lxc-attach -n one-$VM_ID -- mount $loop /media/$DSK_ID" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "sudo losetup -d ${loop}" >> /var/lib/lxc/one-$VM_ID/stop-hook;;
+        	RBD) 	if [ "${DISK_CLONE[${XML_ELEMENT}]}" = "YES" ]; then
+                        	DISK_SOURCE[${XML_ELEMENT}]="${DISK_SOURCE[${XML_ELEMENT}]}-${VM_ID}-${DSK_ID}"
+                        fi
+                	IMAGE_NAME=`echo "${DISK_SOURCE[${XML_ELEMENT}]}" | cut -d '/' -f 2`;
+			echo "#--------------------Mounting disk $DSK_ID on one-${VM_ID}--------------------#" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "RBD_DEV=\$(rbd showmapped | grep -m 1 $IMAGE_NAME | awk '{print \$5}')" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "if [ -z \$RBD_DEV ]; then" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "rbd map $CEPH_AUTH \"${DISK_SOURCE[${XML_ELEMENT}]}\"" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "RBD_DEV=\$(rbd showmapped | grep -m 1 $IMAGE_NAME | awk '{print \$5}')" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "fi" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "lxc-device -n one-$VM_ID add \$RBD_DEV" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "lxc-attach -n one-$VM_ID -- mkdir -p /media/$DSK_ID" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "lxc-attach -n one-$VM_ID -- mount \$RBD_DEV /media/$DSK_ID" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "RBD_DEV=\$(rbd showmapped | grep -m 1 $IMAGE_NAME | awk '{print \$5}')" >> /var/lib/lxc/one-$VM_ID/stop-hook
+			echo "sudo rbd unmap \$RBD_DEV" >> /var/lib/lxc/one-$VM_ID/stop-hook;;
+		BLOCK)  echo "#--------------------Mounting disk $DSK_ID on one-${VM_ID}--------------------#" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "lxc-device -n one-$VM_ID add /dev/vg-one-0/lv-one-${VM_ID}-${DSK_ID}" >> /var/lib/lxc/one-$VM_ID/vnc;
+			echo "lxc-attach -n one-$VM_ID -- mkdir -p /media/$DSK_ID" >> /var/lib/lxc/one-$VM_ID/vnc
+			echo "lxc-attach -n one-$VM_ID -- mount /dev/vg-one-0/lv-one-${VM_ID}-${DSK_ID} /media/${DSK_ID}" >> /var/lib/lxc/one-$VM_ID/vnc;;
+	esac
+fi
+done < <(xmlstarlet sel -t -v "/VM/TEMPLATE/DISK/DISK_ID" -n /var/lib/one/vms/${VM_ID}/deployment.$DEPLOY_NUM)
+
+
+
+cat >> /var/lib/lxc/one-$VM_ID/vnc <<EOF
+## VNC
+if [ -n "\${VM_VNC_PASSWD}" ]; then
+sudo vncterm -timeout 0 -passwd ${VM_VNC_PASSWD} -rfbport $VM_VNC_PORT -c lxc-console -n one-$VM_ID &
+fi
+
+## Setting the VM Hostname after making sure there are no space chars on the hostname
+sleep 3
+sudo lxc-attach -e -n one-$VM_ID -- hostname $VM_HOSTNAME_FIXED
+EOF
+
+echo "if [ \"\$just_reboot\" = \"0\" ]; then" >> /var/lib/lxc/one-$VM_ID/stop-hook
+echo "sudo rm -rf /var/lib/lxc/one-${VM_ID}" >> /var/lib/lxc/one-$VM_ID/stop-hook
+echo "fi" >> /var/lib/lxc/one-$VM_ID/stop-hook
+
+##############################################################################
+#                  	    INICIAR CONTENEDOR VIRTUAL                       #
+##############################################################################
+
+sudo -E lxc-start -d -n one-$VM_ID -f /var/lib/lxc/one-$VM_ID/config
+
+if [ "x$?" = "x0" ]; then
+    echo "one-$VM_ID"
+else
+    error_message "Could not create domain from one-$VM_ID"
+    exit -1
+fi
+
+VM_STATE=$(sudo lxc-ls -f | grep "one-$VM_ID" | awk '{ print $2 }')
+if [ "$VM_STATE" != "RUNNING" ]; then
+	sleep 5
+	VM_STATE=$(sudo lxc-ls -f | grep "one-$VM_ID" | awk '{ print $2 }')
+	if [ "$VM_STATE" != "RUNNING" ]; then
+		sleep 5
+		VM_STATE=$(sudo lxc-ls -f | grep "one-$VM_ID" | awk '{ print $2 }')
+		if [ "$VM_STATE" != "RUNING" ]; then
+			exit -1
 		fi
 	fi
-done < <(echo -e "$XML_PARSE")
+fi
+
+exit 0
+
